Repository p-factory/P-factory-Front, pull requests merged in 2024-11, with the labels that each got.

#25 Position 속성에 대해 알아본다.
  front/src/View/DEV/Position/DevPositionLogin.tsx
Labels: 👨‍💻FE, 🐞Bug, 🌬TailwindCSS

#37 Main 페이지를 tailwindcss로 구현한다.
  .eslintrc.cjs
  front/package.json
  front/src/App.tsx
  front/src/View/Login/Login.in.tsx
  front/src/View/Login/SignUp.tsx
  front/src/View/Main/MainPage.tsx
  front/src/View/Main/ManualPage.tsx
  front/src/View/Main/MyFactory.tsx
  front/src/View/Main/component/Manual.componentBottom.tsx
  front/src/View/Main/component/Manual.componentTop.tsx
  front/src/View/Main/component/MyFactory.component.tsx
  front/src/View/Main/test/MainPage.test.tsx
  front/src/View/Main/test/ManualPage.test.tsx
  front/src/View/Main/test/ManualPage2.test.tsx
  front/src/global/Img/toryLeft.svg
  front/src/global/Img/toryTop.svg
  front/src/global/components/Template.test.tsx
Labels: 👨‍💻FE, 🌬TailwindCSS

#39 VocabularyBook 페이지를 tailwindcss로 구현한다.
  front/src/View/VocabularyBook/VocabularyBookPage.tsx
  front/src/global/Img/pencilIconGrey.svg
Labels: 👨‍💻FE, 🌬TailwindCSS

#42 디자인을 맞추기 위해 Template 컴포넌트의 구조를 수정한다.
  front/src/App.tsx
  front/src/View/Login/Login.tsx
  front/src/View/Main/ManualPage.tsx
  front/src/View/VocabularyBook/VocabularyBookPage.tsx
  front/src/global/components/Template.test.tsx
  front/src/global/components/Template.tsx
Labels: 👨‍💻FE, 🐞Bug, 🌬TailwindCSS

#44 develop 브렌치를 점검하고 전체 Template.test를 적용한다.
  front/src/App.tsx
  front/src/View/Login/Login.id.tsx
  front/src/View/Login/Login.nickname.tsx
  front/src/View/Login/Login.password.tsx
  front/src/global/components/Template.test.tsx
Labels: 👨‍💻FE, 🐞Bug, 🌬TailwindCSS

#45 Login, signup 페이지의 기능을 구현한다.
  front/src/App.tsx
  front/src/View/DEV/img/login-black-logo.svg
  front/src/View/DEV/img/login-white-logo.svg
  front/src/View/Login/Login.component.tsx
  front/src/View/Login/Login.id.component.tsx
  front/src/View/Login/Login.id.tsx
  front/src/View/Login/Login.in.component.tsx
  front/src/View/Login/Login.nickname.component.tsx
  front/src/View/Login/Login.nickname.tsx
  front/src/View/Login/Login.password.component.tsx
  front/src/View/Login/Login.password.tsx
  front/src/View/Login/SignUp.component.tsx
  front/src/View/Login/SignUp.tsx
  front/src/View/Main/ManualPage.tsx
  front/src/View/Main/MyFactory.tsx
  front/src/global/components/Template.test.tsx
Labels: ⚛React, 🌬TailwindCSS

#47 Mocking 서버를 보강하고 다시 점검한다.
  mocking/API/GetHandler.js
  mocking/API/PostHandler.js
  mocking/Routes/createRoutes.js
  mocking/db/db.json
  mocking/db/db.test.name.json
  mocking/db/db.users.json
  mocking/db/mergeData.json
  mocking/db/mergeJSONLoader.js
  mocking/db/routes.json
  mocking/function/createToken.js
  mocking/json.mocking.server.js
  mocking/package.json
  mocking/test/HyperLink.test.js
  mocking/test/createRoutes.test.js
  mocking/test/db/db.json
  mocking/test/db/db.name.json
  mocking/test/db/db.test.json
  mocking/test/db/db.user.json
  mocking/test/db/routes.json
  mocking/test/db/temp/db.multi.json
  mocking/test/db/temp/routes.json
  mocking/test/getName.handler.test.js
  mocking/test/getUser.handler.test.js
  mocking/test/json.mocking.server.test.js
  mocking/test/mocking.server.test.js
  mocking/test/signUp.handler.test.js
Labels: 🐵Mocing, 📡API, 🌿Nodejs

#51 Login, Signup페이지 Mocking API를 연결하고 구현한다.
  front/.env
  front/src/App.tsx
  front/src/Model/atom.ts
  front/src/View/DEV/DevFetch.tsx
  front/src/View/Login/Login.in.component.tsx
  front/src/View/Login/SignUp.id.component.tsx
  front/src/View/Login/SignUp.id.tsx
  front/src/View/Login/SignUp.nickname.component.tsx
  front/src/View/Login/SignUp.nickname.tsx
  front/src/View/Login/SignUp.password.component.tsx
  front/src/View/Login/SignUp.password.tsx
  front/src/global/Hooks/uesFetchSingleAPI.tsx
  mocking/db/db.users.json
  mocking/db/mergeData.json
  mocking/package.json
Labels: 👨‍💻FE, ⚛React, 🐵Mocing

#52 단어장 페이지 컴포넌트 분리를 한다.
  .eslintrc.cjs
  front/package-lock.json
  front/package.json
  front/src/View/VocabularyBook/VocabularyBookPage.tsx
  front/src/View/VocabularyBook/components/VocabularyBook.component.tsx
  front/src/View/VocabularyBook/components/VocabularyBookList.component.tsx
  front/src/View/VocabularyBook/components/VocabularyBookWord.component.tsx
Labels: 👨‍💻FE, ⚛React

#53 단어 생성(MyFactory Page) 모달창을 구현한다.
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/View/Main/MyFactory.tsx
  front/src/global/Img/circleSingleIcon.svg
Labels: ⚛React, 🌬TailwindCSS

#56 develop 브렌치의 전체적인 기능을 점검한다.
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/View/DEV/DevTerminal.tsx
  front/src/View/Login/Login.component.tsx
  front/src/View/Login/Login.in.component.tsx
  front/src/View/Login/SignUp.component.tsx
  front/src/View/Login/SignUp.id.component.tsx
  front/src/View/Login/SignUp.nickname.component.tsx
  front/src/View/Login/SignUp.password.component.tsx
  front/src/View/Login/SignUp.password.tsx
  front/src/View/Main/MainPage.tsx
  front/src/View/Main/ManualPage.tsx
  front/src/View/Main/MyFactory.tsx
  front/src/View/VocabularyBook/VocabularyBookPage.tsx
  front/src/View/test.tsx
  front/src/global/Img/closed.svg
  front/src/global/components/Template.test.tsx
  front/src/global/components/Template.tsx
  front/src/index.css
  package-lock.json
  package.json
Labels: 👨‍💻FE, 🛠Config, ⚛React, 🌬TailwindCSS, 🐵Mocing

#58 단어장 페이지에서 단어 생성과 조회 부분을 구현한다.
  front/src/View/VocabularyBook/VocabularyBookPage.tsx
  front/src/View/VocabularyBook/components/VocabularyBook.component.tsx
  front/src/View/VocabularyBook/components/VocabularyBookList.component.tsx
  front/src/View/VocabularyBook/components/VocabularyBookWord.component.tsx
  mocking/API/GetHandler.js
  mocking/API/PostHandler.js
  mocking/db/db.words.json
  mocking/json.mocking.server.js
  mocking/node_modules/.package-lock.json
  mocking/package-lock.json
Labels: 👨‍💻FE, ⚛React, 🐞Bug, 🐵Mocing
